### ISSUE TITLE
"Open Disk Image File" browser has DnD enabled

### ISSUE THREAD

**Issue by mc4man** [gkovacs/unetbootin#19]
At least in Ubuntu it does & with root permissions.
There is no need for this & can cause the inadvertent moving of a file or folder, particularly with touchpads.
LP bug - 
https://bugs.launchpad.net/ubuntu/+source/unetbootin/+bug/1438236

**Comment by gkovacs** [comment]
Hi I'm the upstream maintainer. No need to get trigger-happy. There is a 4-line fix to this, specifically add the QFileDialog::ReadOnly option to the 4 occurrences of QFileDialog::getOpenFileName in https://github.com/gkovacs/unetbootin/blob/master/src/unetbootin/unetbootin.cpp . I'll update it soon. Thanks!

**Comment by gkovacs** [comment]
fixed in https://github.com/gkovacs/unetbootin/commit/9dafdda9ad6765d27c62df52daa708db22835e3e
