### ISSUE TITLE
UI In Ubuntu enables drag and drop

### ISSUE THREAD

**Issue by shadesoflight** [gkovacs/unetbootin#22]
I just had sudo privileges on the ui and dragged my /lib folder into my /home folder and now all of my shell commands are broken.  Wish me luck fixing this with a live cd...

**Comment by shadesoflight** [comment]
luckily it was an easy fix.  If I hadn't noticed, though, I'd wonder forever what broke my system and why oh why did I try to burn arch linux onto a usb stick using my work computer...

**Comment by shadesoflight** [comment]
If you're going to leave this feature, at least allow me a way of dragging root folders back to root.

**Comment by gkovacs** [comment]
fixed in https://github.com/gkovacs/unetbootin/commit/9dafdda9ad6765d27c62df52daa708db22835e3e

**Comment by shadesoflight** [comment]
:+1:

**Comment by tetsuo-shima** [comment]
@gkovacs What version was this fixed in? I just experienced the same issue that @chadfurman did in Ubuntu 16.04.2.

**Comment by gkovacs** [comment]
@tetsuo-shima 613 and above, which was released in 2015... ubuntu ships with 608 unfortunately as it seems the maintainer in debian has forgotten to update the package
